services:
  database:
    image: postgres:17
    container_name: bd
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  webui:
    build:
      context: ./web-ui
    container_name: web-ui-container
    env_file:
      - ./.env
    restart: always
    depends_on:
      database:
        condition: service_healthy

  telegram:
    build:
      context: ./bot
    container_name: bot-container
    env_file:
      - ./.env
    restart: always
    depends_on:
      - webui



  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - webui
      - telegram

volumes:
  pg_data: