services:
  database:
    image: postgres:17
    container_name: bd
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-ui:
    build:
      context: ./web-ui
    container_name: web-ui-container
    env_file:
      - ./.env
    ports:
      - "8080:80"
    restart: always

  bot:
    build:
      context: ./bot
    container_name: bot-container
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: always

volumes:
  pg_data: