---
# tasks file for setup-items-app
- name: Ensure items-app dir exists
  file:
    path: "{{ prj_dir }}"
    state: directory
    mode: '0755'

- name: Git checkout
  git:
    repo: "https://github.com/TapAleksej/diary.git"
    dest: "{{ prj_dir }}"

- name: Create .env
  copy:
    content: |
              "
              POSTGRES_DB={{ POSTGRES_DB }}
              POSTGRES_USER={{ POSTGRES_USER }}
              POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
              POSTGRES_PORT={{ POSTGRES_PORT }}
              POSTGRES_HOST={{ POSTGRES_HOST }}
              TELEGRAM_TOKEN={{ TELEGRAM_TOKEN }}
              imgweb={{ imgweb }}
              "
    dest: "{{ prj_dir }}/.env"


- name: Start app
  community.docker.docker_compose_v2:
    pull: always
    project_src: "{{ prj_dir }}"
  register: output

- name: Check results
  ansible.builtin.debug:
    var: output