---
- name: Create /app directory
  file:
    path: "{{ prj_dir }}"
    state: directory

- name: git repo clone
  git:
    repo: 'git@github.com:TapAleksej/diary.git'
    dest: "{{ prj_dir }}"

- name: copy env
  template:
    src: env_file.j2
    dest: "{{ prj_dir }}/.env"